<?php
$z[0]=Array("global","@me=(@me+1)%2==0?'':'chosenbox-ml';",22,114);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",153,168);
$z[2]=Array("fulltitle","",177,195);
$z[3]=Array("litpic","",223,238);
$z[4]=Array("fulltitle","",245,263);
$z[5]=Array("arcurl","",319,334);
$z[6]=Array("fulltitle","",343,361);
$z[7]=Array("fulltitle","",379,397);
$z[8]=Array("info","",414,427);

?>