<?php
$z[0]=Array("arclist","\r\n                        <li class=\"clearfix\"> <span class=\"img\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"120\" height=\"80\"/></a> </span> <span><a href=\"[field:arcurl/]\">[field:title/]</a> <em>[field:info/]...</em></span> </li>\r\n              ",86,420);
$z[0][4]['row']="5";
$z[0][4]['titlelen']="32";
$z[0][4]['noflag']="h";
$z[0][4]['infolen']="120";

?>