<div class="zimeiti_center_list" style="display:none">
          <ul>
              {dede:arclist row=5 titlelen=32 noflag='h' infolen='120'}
                        <li class="clearfix"> <span class="img"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="120" height="80"/></a> </span> <span><a href="[field:arcurl/]">[field:title/]</a> <em>[field:info/]...</em></span> </li>
              {/dede:arclist}
           </ul>
        </div>