	
<field:onlynet itemname="联系方式限制" autofield="1" type="int" isnull="true" default="1"  maxlength="250" issearch="" isshow="" state="1">	
</field:onlynet>	
	
<field:sex itemname="性别" autofield="1" type="radio" isnull="true" default="男,女,保密"  maxlength="250" issearch="" isshow="" state="1">	
</field:sex>	
	
	
	
<field:qq itemname="QQ" autofield="1" type="textchar" isnull="true" default=""  maxlength="12" issearch="" isshow="" state="1">	
</field:qq>	
	
<field:msn itemname="微信号" autofield="1" type="textchar" default=""  maxlength="50" issearch="0" isshow="0" state="1">
	
</field:msn>
	
	
<field:tel itemname="电话号码" autofield="1" type="text" isnull="true" default=""  maxlength="15" issearch="" isshow="" state="1">	
</field:tel>	
	
<field:mobile itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="15" issearch="" isshow="" state="1">	
</field:mobile>	
	
	
	
	
	
	
	
<field:birthday itemname="生日" autofield="1" type="datetime" isnull="true" default=""  maxlength="250" issearch="" isshow="" state="1">	
</field:birthday>	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
<field:uptime itemname="更新时间" autofield="1" type="int" isnull="true" default=""  maxlength="10" issearch="" isshow="" state="1">	
</field:uptime>	
