<?php
$z[0]=Array("title","",10,24);
$z[1]=Array("pubdate","",45,96);
$z[1][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[2]=Array("click","",106,120);
$z[3]=Array("arcurl","",168,183);
$z[4]=Array("fulltitle","",209,227);
$z[5]=Array("litpic","",240,255);
$z[6]=Array("fulltitle","",262,280);
$z[7]=Array("description","",329,349);
$z[8]=Array("arcurl","",369,384);
$z[9]=Array("fulltitle","",410,428);

?>