<?php
$z[0]=Array("arcurl","",19,34);
$z[1]=Array("fulltitle","",60,78);
$z[2]=Array("title","",103,117);
$z[3]=Array("pubdate","",142,193);
$z[3][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[4]=Array("click","",203,217);
$z[5]=Array("arcurl","",265,280);
$z[6]=Array("fulltitle","",306,324);
$z[7]=Array("litpic","",337,352);
$z[8]=Array("fulltitle","",359,377);
$z[9]=Array("description","",426,446);
$z[10]=Array("arcurl","",466,481);
$z[11]=Array("fulltitle","",507,525);

?>