<li>		<h3><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]" style="color:#333333;">[field:title/]</a></h3>
					<p><span>[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]    ÔÄ¶Á£º[field:click/]</span></p>
					<div class="testimg"><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]" ><img src="[field:litpic/]" alt="[field:fulltitle/]" width="350" height="242" /></a></div>
					<p>[field:description/]</p>
					<a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]"  class="fulltext">ÔÄ¶ÁÈ«ÎÄ</a>
				</li>