<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",973,1008);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]<i></i></a></li>\r\n      ",1379,1593);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='on'><a href='~typelink~'>~typename~<i></i></a></li>";
$z[6]=Array("field","",1729,1758);
$z[6][4]['name']="position";
$z[7]=Array("field","",1804,1825);
$z[7][4]['name']="content";
$z[8]=Array("include","",1951,1988);
$z[8][4]['filename']="footer.htm";

?>