<?php
$z[0]=Array("field","",334,353);
$z[0][4]['name']="title";
$z[1]=Array("global","",354,380);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",421,450);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",490,548);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1555,1590);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n				<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\"><img src=\"[field:litpic/]\" width=\"670\" height=\"365\"/></a></li>\r\n                ",1834,2049);
$z[5][4]['row']="4";
$z[5][4]['titlelen']="32";
$z[5][4]['flag']="f";
$z[6]=Array("arclist","\r\n				<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">[field:title/]</a></li>\r\n                ",2139,2315);
$z[6][4]['row']="4";
$z[6][4]['titlelen']="32";
$z[6][4]['flag']="f";
$z[7]=Array("arclist","\r\n				<li><div class=\"color[field:global.autoindex/]\">[field:title/]</div></li>\r\n                ",2378,2531);
$z[7][4]['row']="4";
$z[7][4]['titlelen']="32";
$z[7][4]['flag']="f";
$z[8]=Array("arclist","\r\n                     <li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">[field:title/]</a></li>\r\n                  ",2775,2990);
$z[8][4]['flag']="c";
$z[8][4]['row']="9";
$z[8][4]['orderby']="pubdate";
$z[8][4]['titlelen']="34";
$z[9]=Array("list","\r\n                \r\n				<li>		<h3><a href=\"[field:arcurl/]\"  target=\"_blank\" title=\"[field:fulltitle/]\" style=\"color:#333333;\">[field:title/]</a></h3>\r\n					<p><span>[field:pubdate function=\"MyDate('Y-m-d H:i',@me)\"/]    ÔÄ¶Á£º[field:click/]</span></p>\r\n					<div class=\"testimg\"><a href=\"[field:arcurl/]\"  target=\"_blank\" title=\"[field:fulltitle/]\" ><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" width=\"350\" height=\"242\" /></a></div>\r\n					<p>[field:description/]</p>\r\n					<a href=\"[field:arcurl/]\"  target=\"_blank\" title=\"[field:fulltitle/]\"  class=\"fulltext\">ÔÄ¶ÁÈ«ÎÄ</a>\r\n				</li>\r\n                 ",3343,3991);
$z[9][4]['pagesize']="12";
$z[10]=Array("pagelist","",4057,4113);
$z[10][4]['listitem']="pre,next,pageno";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",4319,4356);
$z[11][4]['filename']="footer.htm";

?>