<?php
$typeArr[1] = '观点';
$typeArr[2] = '创投';
$typeArr[3] = '商业';
$typeArr[4] = '智客';
$typeArr[5] = '快报';
$typeArr[6] = '自媒体';
$typeArr[7] = '观点';
$typeArr[8] = '电商';
$typeArr[9] = '传媒';
$typeArr[10] = '通信';
$typeArr[11] = '创业';
$typeArr[12] = '人物';
$typeArr[13] = '关于';
$typeArr[14] = '关于我们';
$typeArr[15] = '寻求报道';
$typeArr[16] = '投稿须知';
$typeArr[17] = '商务合作';
$typeArr[18] = '版权申明';
$typeArr[19] = '联系我们';
$typeArr[20] = '业界';
$typeArr[21] = '手游';
$typeArr[22] = '传媒';
$typeArr[23] = '手机';
?>